// ============================================================================
// Orbit Finance - Contract Addresses
// ============================================================================
// This file is AUTO-GENERATED by .mantle-deploy.sh
// DO NOT EDIT MANUALLY - All changes will be overwritten
// ============================================================================

// Mantle Sepolia Testnet (Chain ID: 5003)
export const CONTRACTS = {
    // Crypto Mode Contracts
    AccountFactory: '0xda796117bf6905dd8db2ff1ab4397f6d2c4adda3' as `0x${string}`,
    DebtManager: '0xa7240bcff60eef40f31b8ed5d921bad6db13b199' as `0x${string}`,
    VaultRegistry: '0xea2e668d430e5aa15baba2f5c5edfd4f9ef6eb73' as `0x${string}`,
    PriceOracle: '0xae7b7a1c6c4d859e19301ccac2c6ed28a4c51288' as `0x${string}`,
    orUSD: '0xc565eb7363769f8ffae0005285ccd854c631a0a0' as `0x${string}`,
    WETH: '0x039d7496e432c6aea4c24648a59318b3cbe09942' as `0x${string}`,
    USDC: '0xbf97defeb6a387215e3e67dfb988c675c9bb1a29' as `0x${string}`,
    WETH_Vault: '0x294c69bd8415219b41b68a2f065deabb950dd489' as `0x${string}`,
    USDC_Vault: '0x48288d0e3079a03f6ec1846554cfc58c2696aaee' as `0x${string}`,
    WETH_Strategy: '0x222d74f33b0d07687a769a44399e2272a4cb9ffe' as `0x${string}`,
    USDC_Strategy: '0x88777418972fb3f58489303d763d4daf398a6527' as `0x${string}`,
    
    // RWA Mode Contracts
    MockUSDC: '0xf102f0173707c6726543d65fa38025eb72026c37' as `0x${string}`,
    IdentityRegistry: '0x5edb3ff1ea450d1ff6d614f24f5c760761f7f688' as `0x${string}`,
    RWAIncomeNFT: '0x81a5186946ce055a5ceec93cd97c7e7ede7da922' as `0x${string}`,
    OrbitRWAPool: '0x98f74b7c96497070ba5052e02832ef9892962e62' as `0x${string}`,
    SPVManager: '0x831c6c334f8ddee62246a5c81b82c8e18008b38f' as `0x${string}`,
    SeniorTranche: '0xf47e3b0a1952a81f1afc41172762cb7ce8700133' as `0x${string}`,
    JuniorTranche: '0xc63db9682ff11707cadbd72bf1a0354a7fef143b' as `0x${string}`,
    WaterfallDistributor: '0xfc3983de3f7cbe1ba01084469779470ad0bbeffa' as `0x${string}`,
    BundlePool: '0xf4c5c29b14f0237131f7510a51684c8191f98e06' as `0x${string}`,
};

// Network Configuration
export const NETWORK = {
    chainId: 5003,
    name: 'Mantle Sepolia Testnet',
    rpcUrl: 'https://rpc.sepolia.mantle.xyz',
    explorer: 'https://sepolia.mantlescan.xyz',
    currency: 'MNT',
};

// Test Account (Anvil default - for reference only)
export const TEST_ACCOUNT = '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266';
